# -*- coding: utf-8 -*-
"""AutoGluon	.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZC1M20Cm87xmDA0pi2VyxDZ42gCpCw5u
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/AIMERS/



pip install autogluon

import pandas as pd
from autogluon.tabular import TabularPredictor

# 데이터 로드
train = pd.read_csv("data/train.csv")
test = pd.read_csv("data/test.csv")

# AutoGluon 모델 학습
predictor = TabularPredictor(label="임신 성공 여부", path="autogluon_model")
predictor.fit(train, presets="best_quality")
# 예측
preds = predictor.predict_proba(test.drop(columns=["ID"]))  # ID 제거 후 예측

# `predict_proba`의 반환값이 DataFrame인지 NumPy 배열인지 확인 후 처리
if isinstance(preds, pd.DataFrame):
    preds = preds.iloc[:, 1]  # DataFrame이면 iloc 사용
else:
    preds = preds[:, 1]  # NumPy 배열이면 일반 인덱싱 사용

# 결과 저장
submission = pd.DataFrame({"ID": test["ID"], "probability": preds})

# 변경된 파일 저장 (선택 사항)
submission.to_csv("submission_autogluon_renamed.csv", index=False, encoding="cp949")



# AutoGluon 모델의 성능 확인
leaderboard = predictor.leaderboard(silent=True)
print(leaderboard)

from google.colab import files
files.download("submission_autogluon_renamed.csv")

submission

