# -*- coding: utf-8 -*-
"""MLJAR Supervised.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DK3hqv1FiPfq8BI_PztJlwkNPzn8e4rU
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/AIMERS/

pip install mljar-supervised

from supervised.automl import AutoML
import pandas as pd

# 📌 데이터 로드
train = pd.read_csv("data/train.csv")
test = pd.read_csv("data/test.csv")

# 🔹 ID 컬럼 저장
test_id = test["ID"]

# 🔹 불필요한 열 제거 (ID는 학습에 필요 없음)
train = train.drop(columns=["ID"])
test = test.drop(columns=["ID"])

# 🔹 특징(X)와 타겟(y) 분리
X_train = train.drop(columns=["임신 성공 여부"])
y_train = train["임신 성공 여부"]

# 📌 MLJAR AutoML 학습
automl = AutoML(mode="Compete", total_time_limit=3600)
automl.fit(X_train, y_train)

# 예측
preds = automl.predict_proba(test)[:, 1]

# `predict_proba`의 반환값이 DataFrame인지 NumPy 배열인지 확인 후 처리
if isinstance(preds, pd.DataFrame):
    preds = preds.iloc[:, 1]  # DataFrame이면 iloc 사용
else:
    preds = preds[:, 1]  # NumPy 배열이면 일반 인덱싱 사용

# 📌 결과 저장 (ID 컬럼 포함)
submission = pd.DataFrame({"ID": test_id, "probability": preds})
submission.to_csv("submission_mljar.csv", index=False, encoding="cp949")
print("\n✅ [결과 저장 완료] 파일: submission_mljar.csv")

from google.colab import files
files.download("submission_mljar.csv")

submission



from supervised.automl import AutoML
import pandas as pd
from sklearn.model_selection import train_test_split

# 데이터 로드
df = pd.read_csv("data/train.csv")

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=["임신 성공 여부"]), df["임신 성공 여부"], test_size=0.2, random_state=42)

# MLJAR AutoML 학습
automl = AutoML(mode="Compete", total_time_limit=3600)
automl.fit(X_train, y_train)

# 예측
preds = automl.predict_proba(X_test)[:, 1]

# 결과 저장
submission = pd.DataFrame({"ID": X_test["ID"], "임신 성공 여부": preds})
submission.to_csv("submission_mljar.csv", index=False)

print("✅ MLJAR AutoML 완료!")